language: java
jdk:
  - openjdk8
before_install:
  - chmod +x mvnw
branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - redgee49@gmail.com 