spring:
  profiles: 
    active: local
apikey: "whdRL7UsbCRRZnkJ8QCflkgArX4qbjSz"
---

spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  h2:
    console:
      enabled: true
